apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev-cluster
  region: us-east-2

managedNodeGroups:
  - name: mng-1-workers
    labels: { role: workers }
    instanceType: t2.small
    volumeSize: 80
    desiredCapacity: 3
    privateNetworking: true
