apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev-cluster
  region: us-east-2

vpc:
  id: '<vpc-id>'
  subnets:
    private:
      us-east-2a:
        id: '<subnet-id>'
      us-east-2b:
        id: '<subnet-id>'
    public:
      us-east-2a:
        id: '<subnet-id>'
      us-east-2b:
        id: '<subnet-id>'

managedNodeGroups:
  - name: mng-1-workers
    labels: { role: workers }
    instanceType: t2.small
    volumeSize: 80
    desiredCapacity: 2
    privateNetworking: true
    ssh:
      allow: true
